Repository moramoram/client, pull requests merged in 2022-03, with the labels that each got.

#368 Feat : div 태그 Semantic 태그로 수정
  src/Layout.jsx
  src/components/commons/Avatar/Avatar.styled.js
  src/components/commons/Badge/Badge.styled.js
  src/components/commons/ImageBox/ImageBox.styled.js
  src/components/commons/ImageBoxResponsive/ImageBoxResponsive.styled.js
  src/components/commons/Input/Input.styled.js
  src/components/commons/SideBarItem/SideBarItem.styled.js
  src/components/layouts/CardGrid/CardGrid.styled.js
  src/components/layouts/CommentList/CommentList.styled.js
  src/components/layouts/FeedGrid/FeedGrid.styled.js
  src/components/layouts/IntroSlider/IntroSlider.styled.js
  src/components/patterns/CardResponsive/CardResponsive.styled.js
  src/components/patterns/Comment/Comment.styled.js
  src/components/patterns/Dropdown/Dropdown.styled.js
  src/components/patterns/Dropdown/DropdownItem/DropdownItem.styled.js
  src/components/patterns/Dropdown/DropdownSmall/DropdownSmall.styled.js
  src/components/patterns/FeedDetail/FeedDetail.styled.js
  src/components/patterns/FeedItem/FeedItem.styled.js
  src/components/patterns/Sidebar/SideBar.styled.js
  src/components/patterns/SubNavbar/SubNavbar.styled.js
  src/components/patterns/SubNavbar/SubNavbarItem/SubNavbarItem.styled.js
  src/containers/CommunityPage/CommunityCreateButton/CommunityCreateButton.styled.js
  src/containers/CommunityPage/CommunityDetail/CommunityDetail.styled.js
  src/containers/CommunityPage/CommunityDetailComment/CommunityDetailComment.styled.js
  src/containers/CommunityPage/CommunityIntro/CommunityIntro.styled.js
  src/containers/JobPage/JobDetail/JobDetail.styled.js
  src/containers/JobPage/JobDetailComment/JobDetailComment.styled.js
  src/containers/JobPage/JobDetailMobile/JobDetailMobile.styled.js
  src/containers/JobPage/JobIntro/JobIntro.styled.js
  src/containers/JobPage/JobMain/JobMain.styled.js
  src/containers/JobPage/JobSideBar/JobSideBar.jsx
  src/containers/JobPage/JobSideBar/JobSideBar.styled.js
  src/containers/MyPage/AuthComplete/AuthComplete.styled.js
  src/containers/MyPage/AuthForm/AuthForm.styled.js
  src/containers/MyPage/MyFeed/MyFeed.styled.js
  src/containers/MyPage/MyInfo/MyInfo.styled.js
  src/containers/MyPage/MyPageIntro/MyPageIntro.styled.js
  src/containers/MyPage/MyPages/MyPages.styled.js
  src/containers/MyPage/MyStudy/MyStudy.jsx
  src/containers/MyPage/MyStudy/MyStudy.styled.js
  src/containers/StudyPage/StudyDetail/StudyDetail.styled.js
  src/containers/StudyPage/StudyDetailComment/StudyDetailComment.styled.js
  src/containers/StudyPage/StudyDetailMobile/StudyDetailMobile.styled.js
  src/containers/StudyPage/StudyIntro/StudyIntro.styled.js
  src/containers/StudyPage/StudyMain/StudyMain.styled.js
  src/containers/StudyPage/StudySideBar/StudySideBar.jsx
  src/containers/StudyPage/StudySideBar/StudySideBar.styled.js
  src/containers/commons/Footer/Footer.styled.js
  src/containers/commons/Navbar/NavDefault/NavDefault.styled.js
  src/containers/commons/Navbar/NavMobile/NavMobile.styled.js
  src/pages/CommunityPage/CommunityPage.jsx
  src/pages/MainPage/MainPage.jsx
Labels: 🙂 FEAT, ✂ REFAC

#371 Feat : 로그인 모달 버튼 css 수정 및 다크모드 추가
  src/components/layouts/SignUpModal/SignUpModal.styled.js
  src/containers/commons/SignUpModal/SignUpModal.styled.js
Labels: 🎨 DESIGN, 🙂 FEAT

#372 Feat : 스터디 채용공고 필터링 기능 수정
  src/containers/JobPage/JobCardGrid/JobCardGrid.jsx
  src/containers/JobPage/JobMain/JobMain.jsx
  src/containers/JobPage/JobMainMobile/JobMainMobile.jsx
  src/containers/StudyPage/StudyCardGrid/StudyCardGrid.jsx
  src/containers/StudyPage/StudyMain/StudyMain.jsx
  src/containers/StudyPage/StudyMainMobile/StudyMainMobile.jsx
  src/recoil/filter.js
Labels: 🙂 FEAT

#374 Feat : 탈퇴 기능 추가
  src/api/deleteUser.js
  src/api/index.js
  src/containers/MyPage/AuthForm/AuthForm.jsx
  src/containers/MyPage/AuthForm/AuthForm.styled.js
  src/containers/MyPage/AuthWait/AuthWait.jsx
  src/containers/MyPage/MyInfo/MyInfo.jsx
  src/containers/MyPage/MyInfo/MyInfo.styled.js
  src/containers/commons/DeleteAccountCompleteModal/DeleteAccountCompleteModal.jsx
  src/containers/commons/DeleteAccountCompleteModal/DeleteAccountCompleteModal.styled.js
  src/containers/commons/DeleteAccountCompleteModal/index.js
  src/containers/commons/DeleteAccountModal/DeleteAccountModal.jsx
  src/containers/commons/DeleteAccountModal/DeleteAccountModal.styled.js
  src/containers/commons/DeleteAccountModal/index.js
  src/containers/commons/index.js
Labels: 🙂 FEAT

#377 Fix : 카드 그리드 관련 오류 수정
  package.json
  public/mac-draco.glb
  src/components/layouts/CardGrid/CardGrid.styled.js
  src/components/patterns/CardResponsive/CardResponsive.styled.js
  yarn.lock
Labels: 🔨 FIX

#380 feat: 메타 데이터 추가 및 open graph 설정
  public/images/apple-touch-icon.png
  public/images/op-image.png
  public/index.html
Labels: 🙂 FEAT

#379 Refac : 탈퇴 모달 컴포넌트 리팩토링
  src/containers/MyPage/AuthWait/AuthWait.jsx
  src/containers/MyPage/DeleteAccountCompleteModal/DeleteAccountCompleteModal.jsx
  src/containers/MyPage/DeleteAccountCompleteModal/DeleteAccountCompleteModal.styled.js
  src/containers/MyPage/DeleteAccountCompleteModal/index.js
  src/containers/MyPage/DeleteAccountModal/DeleteAccountModal.jsx
  src/containers/MyPage/DeleteAccountModal/DeleteAccountModal.styled.js
  src/containers/MyPage/DeleteAccountModal/index.js
  src/containers/MyPage/MyInfo/MyInfo.jsx
  src/containers/MyPage/MyInfo/MyInfo.styled.js
  src/containers/commons/index.js
  src/recoil/modal.js
Labels: ✂ REFAC

#381 Feat/modal
  src/Layout.jsx
  src/containers/CommunityPage/CommunityNoContent/CommunityNoContent.jsx
  src/containers/MyPage/MyPageIntro/MyPageIntro.jsx
  src/containers/MyPage/MyPages/MyPages.jsx
  src/pages/CommunityPage/CommunityPage.jsx
  src/pages/JobPage/JobPage.jsx
  src/pages/StudyPage/StudyPage.jsx
  src/recoil/auth.js
  src/router/PrivateRoute.jsx
  src/router/Router.jsx
Labels: 🙂 FEAT

#385 Fix : Private 라우터 및 채용 공고 관련 에러 전체 수정
  public/robots.txt
  src/Layout.jsx
  src/api/getJobList.js
  src/containers/JobPage/JobDetailMobile/JobDetailMobile.jsx
  src/pages/JobPage/JobPage.jsx
  src/router/Router.jsx
Labels: 🔨 FIX
